# Generated by Django 6.0.7 on 2026-08-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='impuesto (IVA)'),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='subtotal'),
        ),
    ]
