# Generated by Django 6.0.7 on 2026-08-01 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_venta_impuesto_venta_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta (Crédito/Débito)'), ('TRANSFERENCIA', 'Transferencia Bancaria')], default='EFECTIVO', max_length=20, verbose_name='método de pago'),
        ),
    ]
