# Generated by Django 6.0.7 on 2026-08-01 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_venta_detalleventa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
